remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: ADAPQO
description: Adaptive Query Optimization Architectures to Support Heterogeneous Data Intensive Applications

repository: dbr-haslab/adapqo

github:
  is_project_page: false
